### ISSUE TITLE
Error al sellar

### ISSUE THREAD

**Issue by daviidmart** [blacktrue/nodejs-cfdiv33#2]
Al generar el sello veo que firmas todo el xml pero el sello solo debe de estar compuesto por la cadena original firmada. Yo hice un fork y también le añadí soporte para archivos .cer y  .key por la tarde lo subo por si te interesa actualizar tu código .

Validador de facturas: 
https://solucionfactible.com/sfic/validador_factura_electronica/resultadoValidacionCFD.jsp

**Comment by blacktrue** [comment]
@daviidmart no he tenido tiempo de revisar lo que comentas, si haces el PR con gusto lo unimos.

**Comment by blacktrue** [comment]
@daviidmart ya quedo resuelto.
