### ISSUE TITLE
No me permite sellar

### ISSUE THREAD

**Issue by susejreina** [blacktrue/nodejs-cfdiv33#3]
Hola! 

Estoy usando los certificados de prueba del SAT, para generar el .pem utilicé la siguiente instrucción:
`openssl pkcs8 -inform DER -in 'CSD01_AAA010101AAA.key' -passin pass:12345678a -out 'CSD01_AAA010101AAA.key.pem'`

El hecho es que cuando sello,  siempre me da el siguiente error:
'El resultado de la digestión debe ser igual al resultado de la desencripción del sello.'

Si yo agarro el XML generado por la librería, uso esta página para sellarlo:
https://solucionfactible.com/sfic/capitulos/timbrado/sello.jsp#paso2 lo coloco manualmente en el atributo sello y lo mando a timbrar, funciona correctamente.

Crees que me puedas ayudar?

**Comment by blacktrue** [comment]
Hola!

Déjame revisar entre hoy y mañana con los certificados que comentas. de cualquier forma siéntete libre de hacer cambios y realizar un PR

**Comment by susejreina** [comment]
Hola,

El error no estaba en el sello, sino más bien en la formación del XML que se enviaba como cadena original para su sello, ya te hice un pr.

**Comment by blacktrue** [comment]
@susejreina no había tenido tiempo de revisarlo y encontré varios errores. ya libere una nueva versión con las correcciones.
