### ISSUE TITLE
Error *** failed to load external entity "../resources/cadenaoriginal_3_3.xslt" ***

### ISSUE THREAD

**Issue by BeatDeer** [blacktrue/nodejs-cfdiv33#5]
I have an error when run 

warning: failed to load external entity "../resources/cadenaoriginal_3_3.xslt"
cannot parse ../resources/cadenaoriginal_3_3.xslt
 ---> error

**Comment by desert** [comment]
Line 93 of CFDI.js should be:
`const xslt = xsltproc.transform('node_modules/cfdiv33/resources/cadenaoriginal_3_3.xslt', fullPath)`

I think there are better ways to do that but I fixed it temporarily with that.

**Comment by ALEXOTANO** [comment]
I did this and works fine as well, don;t know if @blacktrue is maintaining this repo. 

const xslt = xsltproc.transform(__dirname + '/../resources/cadenaoriginal_3_3.xslt', fullPath)

Great work blacktrue!!!!! save me lot of time!!

**Comment by blacktrue** [comment]
Sorry, I have not had much time to make updates. Thanks for the solution.

He published version 2.1.1 of the package with the fix of @ALEXOTANO 

Please feel free to send me Pull request
